#!/usr/bin/bash
# Set touchpad state.

# Usage
usage () {
  echo "${0##*/} [--off] [--on] - set touchpad state."
} ; [ $# -eq 0 -o $# -gt 1 ] && usage && exit 1

# X.org server command name.
xorgcmd=Xorg.bin
xorgpid=$(pgrep -x $xorgcmd)

# X.org server test if running.
if [ ! "$xorgpid" ]; then
  echo "X.org server is not running."
  exit 1
fi

# Display variable.
# makes assumption that only one DISPLAY is running at a time.
display=$(xargs -0 < /proc/$xorgpid/cmdline | grep " :[0-9] "| grep -o ":[0-9]")
[ "$display" ] || { echo "Display variable un-obtainable."; exit 1; }

# Username variable.
# extremely guessy.
user=$(w | grep " $display " | awk '{ print $1 }')
[ "$user" ] || { echo "User variable un-obtainable."; exit 1; }

# Xauthority location.
if pgrep -x gdm > /dev/null; then
  xauthority=$(find /var/run/gdm -name $user -print -quit)
else
  xauthority=/home/$user/.Xauthority
fi
[ -f "$xauthority" ] || { echo "Xauthority variable un-obtainable."; exit 1; }

syndcmdfile=/tmp/touchpad-state-syndaemon.cmdline
case $1 in
  --off )
    # syndaemon disable if running.
    if syndpid=$(pgrep -x syndaemon); then
      # record command line options and arguments.
      sed 's/\x00/ /g' /proc/$syndpid/cmdline > "$syndcmdfile"
      killall syndaemon
    fi

   # touchpad disable.
    if [ "$user" = $USER ]; then
      DISPLAY=$display XAUTHORITY=$xauthority bash -c '\
        synclient TouchpadOff=1
        notify-send --hint=int:transient:1 "Touchpad disabled."' &
    else
      DISPLAY=$display XAUTHORITY=$xauthority su $user - -c '\
        synclient TouchpadOff=1
        notify-send --hint=int:transient:1 "Touchpad disabled."' &
    fi ;;
  --on )
    # syndaemon run if run previously and not running now.
      if [ -f "$syndcmdfile" ] && ! pgrep -x syndaemon > /dev/null; then
        $(< "$syndcmdfile") -d
        rm "$syndcmdfile"
      fi

    # touchpad enable.
    if [ "$user" = $USER ]; then
      DISPLAY=$display XAUTHORITY=$xauthority bash -c '\
        synclient TouchpadOff=0
        notify-send --hint=int:transient:1 "Touchpad enabled."' &
    else
      DISPLAY=$display XAUTHORITY=$xauthority su $user - -c '\
        synclient TouchpadOff=0
        notify-send --hint=int:transient:1 "Touchpad enabled."' &
    fi ;;
  * ) usage && exit
esac

# vim: set ft=sh ts=2 sw=2 et:
